pipeline:
  changelog:
    image: lawnchairlauncher/drone-changelog:latest
    output: changelog.txt
    when:
      event: push
  build:
    image: runmymind/docker-android-sdk:ubuntu-standalone
    secrets: [ store_password, key_password ]
    environment:
      - MAJOR_MINOR=alpha
      - TRAVIS=true
      - TRAVIS_BUILD_NUMBER=${DRONE_BUILD_NUMBER}
      - TRAVIS_EVENT_TYPE=${DRONE_BUILD_EVENT}
    commands:
      - bash ./gradlew assembleAospCiOptimized;
  deploy:
    image: paphonb/drone-telegram:latest
    secrets: [ bot_token, channel_id, dev_channel_id ]
    environment:
      - APK_PATH=build/outputs/apk/aospCi/optimized/LawnchairWIP-aosp-ci-optimized.apk
      - MAPPING_PATH=build/outputs/mapping/aospCi/optimized/mapping.txt
      - MAJOR_MINOR=v2-alpha
    when:
      event: push
      status: success
  telegram:
      image: appleboy/drone-telegram:latest
      secrets: [ bot_token, dev_channel_id ]
      token: ${BOT_TOKEN}
      to: ${DEV_CHANNEL_ID}
      message: >
        {{#success build.status}}
          Build {{build.number}} succeeded. Good job mate!
        {{else}}
          Build {{build.number}} failed. Fix me please sir!
        {{/success}}

branches:
  include: v2-alpha