pipeline:
  build:
    image: runmymind/docker-android-sdk:alpine-standalone
    environment:
      - MAJOR_MINOR=1.1.0
    commands:
      - bash ./gradlew assembleDebug check;
  telegram:
    image: lawnchairlauncher/docker-telegram:latest
    when:
      event: push
      status: success

branches:
  include: alpha
