pipeline:
  changelog:
    image: lawnchairlauncher/drone-changelog:latest
    output: changelog.txt
    when:
      event: push
  build:
    image: runmymind/docker-android-sdk:alpine-standalone
    environment:
      - MAJOR_MINOR=1.1.0
    commands:
      - bash ./gradlew assembleDebug check;

branches:
  include: alpha
