pipeline:
  changelog:
    image: lawnchairlauncher/drone-changelog:latest
    output: changelog.txt
    when:
      event: push
  build:
    image: runmymind/docker-android-sdk:ubuntu-standalone
    secrets: [ store_password, key_password ]
    environment:
      - MAJOR_MINOR=alpha
      - TRAVIS=true
      - TRAVIS_BUILD_NUMBER=${DRONE_BUILD_NUMBER}
      - TRAVIS_EVENT_TYPE=${DRONE_BUILD_EVENT}
    commands:
      - bash ./gradlew assembleAospCiOptimized;
  deploy:
    image: paphonb/drone-telegram:latest
    secrets: [ bot_token, channel_id ]
    environment:
      - APK_PATH=build/outputs/apk/aospCi/optimized/LawnchairWIP-aosp-ci-optimized.apk
      - MAJOR_MINOR=v2-alpha
    when:
      event: push
      status: success

branches:
  include: v2-alpha