pipeline:
  changelog:
    image: lawnchairlauncher/drone-changelog:latest
    environment:
      - MAJOR_MINOR=alpha
    output: changelog.txt
    when:
      event: push
  build:
    image: runmymind/docker-android-sdk:alpine-standalone
    environment:
      - MAJOR_MINOR=alpha
      - SEPERATOR='-'
      - TRAVIS=true
      - TRAVIS_BUILD_NUMBER=${DRONE_BUILD_NUMBER}
      - TRAVIS_EVENT_TYPE=${DRONE_BUILD_EVENT}
    commands:
      - bash ./gradlew assembleDebug check;

branches:
  include: alpha
